// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "86708c29-8dfe-49f6-936a-e5d8d81230a2";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onD1Change();
void onD2Change();
void onSbChange();

int d1;
int d2;
bool sb;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(d1, READWRITE, ON_CHANGE, onD1Change);
  ArduinoCloud.addProperty(d2, READWRITE, ON_CHANGE, onD2Change);
  ArduinoCloud.addProperty(sb, READWRITE, ON_CHANGE, onSbChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
